/*
 * Automatically generated by jrpcgen 1.0.7 on 13-6-20 ÏÂÎç5:55
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package cn.jos.vxi11.rpc;
/**
 * A collection of constants used by the "vxi11" ONC/RPC program.
 */
public interface vxi11 {
    public static final int DEVICE_CORE = 0x0607AF;
    public static final int device_trigger_1 = 14;
    public static final int DEVICE_ASYNC_VERSION = 1;
    public static final int device_read_1 = 12;
    public static final int DEVICE_CORE_VERSION = 1;
    public static final int destroy_intr_chan_1 = 26;
    public static final int device_lock_1 = 18;
    public static final int device_remote_1 = 16;
    public static final int destroy_link_1 = 23;
    public static final int device_docmd_1 = 22;
    public static final int device_unlock_1 = 19;
    public static final int device_readstb_1 = 13;
    public static final int device_local_1 = 17;
    public static final int device_enable_srq_1 = 20;
    public static final int device_abort_1 = 1;
    public static final int device_clear_1 = 15;
    public static final int create_intr_chan_1 = 25;
    public static final int device_intr_srq_1 = 30;
    public static final int DEVICE_INTR = 0x0607B1;
    public static final int DEVICE_INTR_VERSION = 1;
    public static final int create_link_1 = 10;
    public static final int device_write_1 = 11;
    public static final int DEVICE_ASYNC = 0x0607B0;
}
// End of vxi11.java
