/*
 * Automatically generated by jrpcgen 1.0.7 on 13-6-20 ÏÂÎç5:55
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package cn.jos.vxi11.rpc;
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class vxi11_DEVICE_INTR_ServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public vxi11_DEVICE_INTR_ServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public vxi11_DEVICE_INTR_ServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public vxi11_DEVICE_INTR_ServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(vxi11.DEVICE_INTR, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 30: {
                Device_SrqParms args$ = new Device_SrqParms();
                call.retrieveCall(args$);
                device_intr_srq_1(args$);
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProgramUnavailable();
        }
    }

    public abstract void device_intr_srq_1(Device_SrqParms arg1);

}
// End of vxi11_DEVICE_INTR_ServerStub.java
